### ISSUE TITLE
Embed wizard: open viewer to an annotation

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#163]
The following language exists on step 2 of the embed wizard:
"Tell the viewer to open directly to a specific page or annotation."

However, the wizard does not let you specify an annotation to open directly to. Need to enable that functionality or drop the language for clarity.

**Comment by reefdog** [comment]
Was going to temporarily remove "or annotation" until we added the notes to the menu, but trickling that through all the translations would take as much time as just adding notes to the menu.

**Comment by reefdog** [comment]
So the groundwork for this is there, but [`doc.get('annotation_count')`](https://github.com/documentcloud/documentcloud/blob/master/app/views/jst/workspace/workspace/document_embed_dialog.jst#L65) is [falling back to 0](https://github.com/documentcloud/documentcloud/blob/master/app/models/document.rb#L814).

Everything after that annotation count works; if I remove that conditional on a doc that has notes, choosing "Notes ..." from the menu springs a filled/usable note selection menu.

**Comment by reefdog** [comment]
@knowtheory Was able to pseudo-fix this by correctly looking at `public_note_count` instead of `annotation_count`, but a secondary/related/? problem: `public_note_count` either isn't being reset, or the count available to the embed dialog is stale.

1. Go to a document with no public notes
2. Open document embed dialog, go to Step 2, look in "Viewer opens to" menu
3. Shouldn't (and correctly doesn't) have a "Notes ..." item
4. Close embed dialog
5. Create public note on the document
6. Repeat Step 2
7. Should (and **incorrectly doesn't**) have a "Notes ..." item
8. Refresh page
9. Repeat Step 2
10. Should (and correctly does) have a "Notes ..." item
11. Close embed dialog
12. Delete that note
13. Repeat Step 2
14. Shouldn't (and **incorrectly does**) have a "Notes ..." item
15. Refresh page
16. Repeat Step 2
17. Shouldn't (and correctly doesn't) have a "Notes ..." item

Step 14 is bad but at least we catch it with a "This document has no public notes" message, but Step 7 is very confusing because the only way to get the Notes menu to appear is to refresh the page.

**Comment by reefdog** [comment]
Come to think of it… given that the instruction text references notes and isn't conditional, that the count easily gets stale on this step of the dialog, and that we gracefully handle someone selecting "Notes ..." from the menu if there are none, this shouldn't be conditional.

**Comment by anthonydb** [comment]
Thank you, @reefdog!

**Comment by reefdog** [comment]
:+1:
