### ISSUE TITLE
Please update the INSTALL file

### ISSUE THREAD

**Issue by livelifelively** [documentcloud/documentcloud#181]
the INSTALL file is 2 years old with many dependencies outdated. I am working on implementing documentCloud for a project, please update the install file and instructions.

**Comment by reefdog** [comment]
Hey @livelifelively, this probably isn't the greatest news, but updating the documentation (and streamlining the install) is a pretty big task that we aren't able to tackle at the moment, and we're still trying to decide how self-installation fits into our roadmap. Since broken installation instructions sends the wrong message, I've removed them entirely.

What's the project you're wanting self-install for? We might be able to offer some guidance.

**Comment by livelifelively** [comment]
Hey @reefdog, I understand that updating it all is a lot of work. 

In India, we have a right to information but the open official documents are in a very poor state. I am working on a project where we would get official documents and provide computational operation interfaces on them. DocumentCloud is the perfect solution, so, I am trying to create a mirror of it. 

So far I tried to use the install file to get all the packages and also read the comments on commits to get some idea out of it. But it was quite difficult and hence this issue. 

The best case would be an open channel with consistent communication towards full implementation. In that case I can contribute on the documentation of the project (like the install file). 

I really wish its possible, but if not, at the minimum I would need help on how different components are interlinked and what are their dependencies. There must be some document or logs or whatever, that is being regularly updated and holds the information about the state of they system in entirety. Objective is that even if you cannot help personally, it would be great if I have something that can be used to understand they system. In that case also I will help with docu

**Comment by herbsmn** [comment]
It's been a while since you've closed this ticket. explaining how to self install free software seems super important to me. i'm curious if the project has recently discussed how self-installation fits into its roadmap. is it, in your opinion, possible to self host documentcloud in its current form? if so, would there be features that exist in the centralized hosted version that wouldn't work on a self hosted version? I love documentcloud and think it would be even better if the servers it runs on were more decentralized instead of there being only one.

**Comment by herbsmn** [comment]
You spoke at #StealMyTool twice @knowtheory, but it doesn't seem very easy for news organizations to actually "steal" documentcloud. I see that @DavidLemayian "stole" it, which was beneficial for documentcloud: https://twitter.com/IJNet/status/743877305664077824 Unfortunately he doesn't show how to install his version of documentcloud either: https://github.com/CodeForAfrica/sourceAFRICA/blob/master/INSTALL.md

**Comment by webster** [comment]
I understand that maintaining and supporting open source software is a time-consuming and difficult task,  with no profit and little thanks. But the lack of documentation—chiefly, installation instructions—are a major inhibitor to people benefiting from the fact that this project is OSS, and making contributions themselves. Thanks.

**Comment by DavidLemayian** [comment]
@herbsmn Agreed. DocumentCloud wasn't a walk in the park setting up initially. It took a lot of hacking but we finally cracked it. We tried to document our steps as best as we could a while back which you can find [here](https://gist.github.com/DavidLemayian/26deeeb277a32ca0910a); but have since opted to use the setup scripts that can be found [here](https://github.com/documentcloud/documentcloud/tree/master/config/server/scripts).

Undoubtedly these aren't ideal solutions and still have a high barrier to re-use, but hopefully without overstepping or misquoting I'd like to mention that @knowtheory is actually working on making DocumentCloud _Dockerized_. Meaning it should be much easier for anyone to get set up with a local instance.

cc @webster

**Comment by herbsmn** [comment]
Thanks for the response @DavidLemayian. @knowtheory, can you confirm that a Dockerized version of DocumentCloud is being worked on? Also, may I suggest that you put the old install docs back in the Install file with a note at the top saying that they need updated and it'd be great if someone from the community could supply a pull request?

**Comment by JakeChampion** [comment]
I found this PR from a while back which aimed at making a Dockerized version of the service - https://github.com/documentcloud/documentcloud/pull/119

Is that the latest attempt at Dockerizing or is the work being done inside a different repository?

**Comment by herbsmn** [comment]
Can you please un-close this issue until it is resolved?
