### ISSUE TITLE
Alternative to document.write for JS loading?

### ISSUE THREAD

**Issue by ivarvong** [documentcloud/documentcloud#230]
`https://s3.amazonaws.com/s3.documentcloud.org/embed/loader.js` uses `document.write` to load Javascript. This doesn't work after the DOM is loaded. One use case for this (and the one that affects me) is sites that lazy-load articles.

**Comment by knowtheory** [comment]
Yeah so lets talk about what the loader does.

The loader's designed to load some CSS, provide a configuration point for pixel-ping, and acts as the mechanism that actually inserts/loads the request for app code (by `document.write`ing the app code script tag).  If the app code has already loaded then each run of the loader simply shortcuts and doesn't bother reinserting the app code script tag.

Dynamically injecting the loader removes this possibility because you can't document.write from a dynamically inserted script.  

That in turn would mean that the app code would need to be included as a separate script tag.  That's probably okay from a bandwidth POV, since browsers should cache a resource to be reused.  The code would obviously be *run* again (but that could be shortcutted w/in the app code itself).  What i'm not sure about is whether it's re-parsed/lexed or not (although maybe that's a moot point).

I think what this really means is that the loader as a mechanism is probably not suited for cases like this and we're going to basically have to jam everything into a single file (that shortcuts when executed multiple times) the same way that twitter does.

**Comment by reefdog** [comment]
Fixed in #418
