### ISSUE TITLE
Entity display missing some entity types after upgrade to OpenCalais's v2 API

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#264]
@DavidLemayian reports that after upgrading to master (and uploading an identical document) that several entity types aren't appearing (in this case, Country, State, Email, and Place).

DocumentCloud does some light filtering of the Calais entities before inserting them into our database according to [our entity mapping](https://github.com/documentcloud/documentcloud/blob/master/config/initializers/entity_map.rb).  There may be a problem with how the keys are mapping up with the new gem results, or something going on in the calais gem that we should check out.

![image](https://cloud.githubusercontent.com/assets/192/9523400/d1192dd0-4ca7-11e5-881e-4c29fb197de4.png)

**Comment by cometman** [comment]
This bug has was caused due to the recent migration to the PRX gem.  There were to breaking changes in this upgrade. 

__Issue 1: Change in response hash format__
In the previous Open Calais gem, the response object hash contained __TYPE__ keys that did not have white space (e.g. camel cased/snake casing).  The new PRX gem passed back __TYPE__ keys as strings with white space.  This created problems for the following method: `DC::CALAIS_MAP[string.underscore.to_sym]` [seen here](https://github.com/documentcloud/documentcloud/blob/master/app/models/entity.rb#L23).  The required fix was to replace change manually snake case the key `DC::CALAIS_MAP[string.downcase.tr(" ", "_").to_sym]`

__Issue 2: Locations not included in entities__
The new PRX gem did not include __Locations__ in the `entities` method.  Fix required combining locations and entities into the response array  [seen here] (https://github.com/documentcloud/documentcloud/blob/47c4af807fad31414e8b7601b331700fca7b216a/lib/dc/import/entity_extractor.rb#L49).

**Comment by DavidLemayian** [comment]
Just a question: once this is patched, will there be an easy way to re-run the entity extraction for all the documents?

**Comment by knowtheory** [comment]
@DavidLemayian yep, there's currently a `reprocess_entities` CloudCrowd action (which will be renamed to `process_entities` soon, but will do the same thing).

**Comment by DavidLemayian** [comment]
@knowtheory Thanks! Will look out for the change. Best action would be to run the action in console for every 5k limit or does it handle it alright?

**Comment by cometman** [comment]
Need a to get our hands on an account that has a few documents that were processed with the old Calais system in order to compare to the new Calais. First need to see if have a DocumentCloud account with some documents we can test against.

**Comment by knowtheory** [comment]
[There are a lot of documents to choose from](http://documentcloud.org/public/search)

Just type some search terms and find some docs w/ some entities on them.

**Comment by cometman** [comment]
NEW Calais Extraction
![screen shot 2015-09-23 at 11 04 43 am](https://cloud.githubusercontent.com/assets/1221486/10050628/f8197f70-61e2-11e5-9c7f-4bdb4f5f1b53.png)

OLD Calais Extraction
![screen shot 2015-09-23 at 11 04 48 am](https://cloud.githubusercontent.com/assets/1221486/10050639/0640f808-61e3-11e5-954c-e5d95c6bec77.png)

**Comment by cometman** [comment]
From the results above, apart from small discrepancies the the occurrences, the new upgrade is missing __Terms__ from the result set.  Will go through the new gem and identify the reason for why terms are not being included.

**Comment by cometman** [comment]
Few notes on some findings:

- Middle initials are now being included on person name entities with new API. 
- People entity extraction is identical in current testing
- Places extraction missed a few entities in the new API.  Some of these should have definitely been picked up, as there is not much context ambiguity (like the place _UN HQ_).

**Comment by anthonydb** [comment]
The page for the [new OpenCalais API](http://new.opencalais.com/) talks about "a new and enhanced tagging engine – offering higher quality and higher performance metadata."

Given that, we might not reasonably expect a 1:1 match in entities provided under the old/new versions, correct?

**Comment by cometman** [comment]
Term entity extraction has been resolved by applying a previous fix that was not merged in.  Data was not being stored correctly due to a formatting change of key names in hashes when we changed to a different Calais gem.  https://github.com/documentcloud/documentcloud/commit/ef8e437f1ddb08efee66f065b40274b977fafa70
