### ISSUE TITLE
Proposal: Unify embed loaders

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#282]
Currently we have 3 separate loaders, one for the [Document Viewer](https://github.com/documentcloud/document-viewer/), one for [notes](https://github.com/documentcloud/documentcloud-notes), one for [search embed](https://github.com/documentcloud/dc-search-embed), and soon one for [pages](https://github.com/documentcloud/documentcloud-pages).

@reefdog and i have discussed unifying our loaders into a single file that routes is capable of providing routing logic and identifying several possible types of embed codes and loading the code appropriate to each type.

**Comment by reefdog** [comment]
We'll have to support existing loader endpoints in perpetuity:

- Documents: `/viewer/loader.js`
- Notes: `/notes/loader.js`
- Search: `/embed/loader.js`

The page embed loader is already designed to be resource-agnostic, though it doesn't actually implement that design yet. For semantic purposes I'd recommend we launch it at `/embed/loader.js` with support for pages and searches. Then, over time, we can add support for documents and notes.

**Comment by reefdog** [comment]
We ended up launching the page embed loader at `/embed/loader/enhance.js` rather than try to combine it with search embed's `/embed/loader.js`.

It's highly likely that new generations of the embeds will use `enhance.js`, but highly unlikely we'll actually fold existing loaders into it, considering we have to keep them alive at their existing URLs anyway.

So while this is a good thing, it's more of a guiding principle for the next generation of embeds than a tactical task, so I'm closing. @knowtheory reopen if you disagree.
