### ISSUE TITLE
Which version of tesseract

### ISSUE THREAD

**Issue by phatvoEA** [documentcloud/documentcloud#473]
Hi, I wonder if which version of Tesseract that you are using with Documentcloud at the moment (3 or 4)
Thanks,

**Comment by DavidLemayian** [comment]
Hey @phatvoEA . Currently, because support is on `xenial`, it is using Tesseract 3 (https://packages.ubuntu.com/xenial/tesseract-ocr-dev). We (@CodeForAfrica) haven't tested with 4 yet though on DocumentCloud.

Xenial Ref: https://github.com/documentcloud/documentcloud/blob/master/config/server/scripts/setup_webserver.sh#L14

Tesseract Install: https://github.com/documentcloud/documentcloud/blob/master/config/server/scripts/setup_common_dependencies.sh#L58
