### ISSUE TITLE
Need language/font packs on servers

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#94]
LibreOffice converts word docs w/ non-english characters into PDFs into unicode blocks.

**Comment by nathanstitt** [comment]
This now works, probably because we installed the fonts for Chinese, Japanese, and Korean in https://github.com/documentcloud/documentcloud/commit/05ac44744232845f4ed5d0737ec1148707d26575

However the sample document that you linked to did fail initially because the MD5 matched a previous uploaded.  That caused it's image assets (with UTF blocks) to be copied, rather than re-generated.

It imported correctly after I opened it and added a line break and then re-saved it.

**Comment by reefdog** [comment]
Confirmed that this now works, though we'd hoped to use Google's font pack that has something defined for all unicode codepoints; haven't figured out how to make that work yet, but separate issue.
